// Generated by CoffeeScript 1.7.1
(function() {
  var DIR, app, configFile, counter, express, fs, path, port, serveErrorMessage;

  express = require('express');

  fs = require('fs');

  path = require('path');

  counter = 0;

  configFile = path.resolve('./config.json');

  DIR = JSON.parse(fs.readFileSync(configFile)).dir;

  console.log('Current output dir: ' + DIR);

  app = express();

  serveErrorMessage = function(error, msg, res) {
    var message;
    console.log(error);
    message = {
      "status": "error",
      "message": msg
    };
    res.type('text/json');
    return res.send(message);
  };

  app.get('/mobilerest/', function(req, res) {
    var filepath, restaurant, restaurantDir, week, year;
    restaurant = req.query.restaurant;
    restaurantDir = restaurant + '/';
    year = req.query.year;
    week = req.query.week;
    filepath = DIR + restaurantDir + year + '_w' + week + '_' + restaurant + '.json';
    fs.readFile(filepath, 'utf8', function(err, data) {
      var msg;
      if (err) {
        msg = "File not available - Bad restaurant name or week number: " + restaurant + " " + week;
        serveErrorMessage(err, msg, res);
      } else {
        res.type('text/json');
        return res.send(data);
      }
    });
    console.log('Client queried for: ' + JSON.stringify(req.query));
    return console.log('Answered to request #' + (++counter));
  });

  app.get('/mobilerest/queryAllUnicaNewest', function(req, res) {
    var currentDate, filepath, week, year;
    currentDate = new Date();
    year = currentDate.getFullYear();
    week = currentDate.getWeek();
    filepath = DIR + 'unica/' + year + '_w' + week + '_' + 'unica.json';
    return fs.readFile(filepath, 'utf8', function(err, data) {
      var msg;
      if (err) {
        msg = "File not available - Bad week number: " + week;
        serveErrorMessage(err, msg, res);
        return;
      }
      res.type('text/json');
      res.send(data);
      console.log('Client queried for: ' + JSON.stringify(req.query));
      return console.log('Answered to request #' + (++counter));
    });
  });

  app.get('/mobilerest/log', function(req, res) {
    var filepath;
    filepath = '../../log';
    return fs.readFile(filepath, 'utf8', function(err, data) {
      var msg;
      if (err) {
        msg = "Logfile not available";
        serveErrorMessage(err, msg, res);
        return;
      }
      res.type('text/plain');
      return res.send(data);
    });
  });

  Date.prototype.getWeek = function() {
    var dayNr, firstThursday, target;
    target = new Date(this.valueOf());
    dayNr = (this.getDay() + 6) % 7;
    target.setDate(target.getDate() - dayNr + 3);
    firstThursday = target.valueOf();
    target.setMonth(0, 1);
    if (target.getDay() !== 4) {
      target.setMonth(0, 1 + ((4 - target.getDay()) + 7) % 7);
    }
    return Math.ceil(1 + (firstThursday - target) / 604800000);
  };

  port = process.env.PORT || 4730;

  console.log("Listening on port " + port);

  app.listen(port);

}).call(this);
