// Generated by CoffeeScript 1.6.3
(function() {
  var DIR, app, counter, express, fs;

  express = require('express');

  fs = require('fs');

  counter = 0;

  DIR = JSON.parse(fs.readFileSync('config.json')).dir;

  console.log('Current output dir: ' + DIR);

  app = express();

  app.get('/', function(req, res) {
    var filepath, restaurant, week, year;
    restaurant = req.query.restaurant;
    year = req.query.year;
    week = req.query.week;
    filepath = DIR + year + '_w' + week + '_' + restaurant + '.json';
    fs.readFile(filepath, 'utf8', function(err, data) {
      if (err) {
        console.log(err);
        res.type('text/plain');
        res.send('ERROR 404: file not found');
        return;
      }
      res.type('text/json');
      return res.send(data);
    });
    console.log('Client queried for: ' + JSON.stringify(req.query));
    return console.log('Answered to request #' + (++counter));
  });

  app.listen(process.env.PORT || 4730);

}).call(this);
