// Generated by CoffeeScript 1.6.3
(function() {
  var DIR, app, counter, express, fs;

  express = require('express');

  app = express();

  counter = 0;

  fs = require('fs');

  DIR = JSON.parse(fs.readFileSync('config.json')).dir;

  console.log('Current output dir: ' + DIR);

  app.get('/', function(req, res) {
    var restaurant, week, year;
    res.type('text/json');
    restaurant = req.query.restaurant;
    year = req.query.year;
    week = req.query.week;
    fs.readFile(DIR + year + '_w' + week + '_' + restaurant + '.json', 'utf8', function(err, data) {
      if (err) {
        console.log(err);
        res.type('text/plain');
        res.send('ERROR 404: file not found');
      }
      return res.send(data);
    });
    console.log('Client queried for: ' + JSON.stringify(req.query));
    return console.log('Answered to request #' + (++counter));
  });

  app.listen(process.env.PORT || 4730);

}).call(this);
